# Generated by Django 6.0.5 on 2026-08-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetmaterial',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='stock disponible'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='correo electronico'),
        ),
    ]
