# Generated by Django 6.0.5 on 2026-08-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetmaterial',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='stock disponible'),
        ),
    ]
